FROM registry.cn-shanghai.aliyuncs.com/mathits/its:base-rest-image as build

ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive

RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

COPY package.json /app/package.json
COPY .npmrc /app/.npmrc

RUN yarn
COPY . /app/
RUN yarn build

CMD ["npm", "start"]
