FROM registry.cn-shanghai.aliyuncs.com/mathits/hy:base-server-image as build

WORKDIR /app/
COPY package.json ./package.json
COPY yarn.lock ./yarn.lock
RUN yarn
COPY . ./

ENV PATH=/app/node_modules/.bin:$PATH
RUN echo $PATH
SHELL [ "/bin/bash", "-c"]
RUN yarn test

RUN yarn m:check || yarn m:run
RUN yarn m:check


