FROM lvvapflt.mirror.aliyuncs.com/library/node:16
ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive

RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/
COPY package.json ./package.json
COPY yarn.lock ./yarn.lock

RUN yarn
